### ISSUE TITLE
PS4 Left axis gets mapped to RT

### ISSUE THREAD

**Issue by Pices-26** [ApproxEng/approxeng.input#37]
After changing mapping in dualshock4.py still nothing,
Also inversion doesn't work on any axis.
I'm working on jetson nano

**Comment by tomoinn** [comment]
If changing the file doesn't make any difference you need to fix your project setup - it's not being affected by anything else! I'd recommend using a virtual environment and then using 'python setup.py develop' to symlink the source directly, that way any updates you make to the code will appear immediately.

Inversion isn't functional at all, the API is simplified so rather than doing e.g. range 0..10 invert=True you do range 10..0, flip the min and max values (think of them as 'reported value at min position / max position' rather than 'minimum reported value')
