### ISSUE TITLE
Issues with Output Values

### ISSUE THREAD

**Issue by TJQuin** [ApproxEng/approxeng.input#41]
I installed xpadneo to help with button mapping, which it did fix that, but I also have one more issue that has been occurring.  I will press and hold the right trigger of my X Box One S controller and it will give a value of one, but when I release, it will not become zero and will instead output a lower number (from about usually 0.01 to 0.5 or so).  When I release slowly it goes all the way down but is there a way to make sure it actually outputs zero when the triggers are released?  There also seems like there is a similar issue with the sticks where they work well when being moved around, but when they are released, they have a random value that keeps being output.  Any help is appreciated.

**Comment by TJQuin** [comment]
What I've seen with more experimentation is that the rx and lx go from -1 to 0 and ry and ly go from 0 to 1.  Being that they are centered axes, should they not all output values from -1 to 1 and then letting the stick in the middle would be 0?  The stick keeping a random number while not being used really throws me off.

**Comment by tomoinn** [comment]
I suspect there are two things here.

1) It's possible that xpadneo is interfering or changing the value ranges, I don't know because the controllers work without it for me (when I last checked, I'll do another sweep through all the controller types with the lastest Pi OS at some point soon)

2) The slow release is quite possibly an IO issue. Are you by any chance running a very tight loop with a print() statement in it? If so, try adding a short sleep() in the loop - this tends to happen in trivial test cases, in real applications there's enough other stuff going on in your control loop that it's not an issue but printing to the console seems to interfere with the IO used to read events if you do it too fast.

**Comment by TJQuin** [comment]
Ok so I was having a problem without xpadneo before but uninstalling it did fix the axis range issue.  It did make some of the button mapping a bit weird but I fixed everything except that the right stick controls the left and right triggers but when I switch the xboxone.py file to try to counteract that, the triggers still do not output anything though the right stick outputs its correct values. I just have the button presses printed as shown below in a bit of my test code. This is what I have in my xboxone.py file
[xboxone.txt](https://github.com/ApproxEng/approxeng.input/files/5256615/xboxone.txt)
This is my testing code, and I just comment out what I don't want to output
    #checks to see which button is pressed
    rt_held = joystick['r2']
    rt_analog = joystick['rt']
    if rt_held is not None:
        print('right trigger: ' + str(rt_analog))
    lt_held = joystick['l2']
    lt_analog = joystick['lt']
    if lt_held is not None:
        print('left trigger: ' + str(lt_analog))
    if (rt_held == None) and (lt_held == None):
        lstick_x = joystick['lx']
        lstick_y = joystick['ly']
        rstick_x = joystick['rx']
        rstick_y = joystick['ry']
        print('left and right ' + str(lstick_x))
        print('forward and back ' + str(lstick_y))
        print('right stick X ' + str(rstick_x))
        print('right stick Y ' + str(rstick_y))
        time.sleep(0.1)

**Comment by tomoinn** [comment]
Are you using a wired or bluetooth interface? They'll be different values, annoyingly. Also have you ever connected this controller to an XBox or windows PC as a game controller, because, again, that will make a difference (it updates the controller firmware). Finally, what linux distribution, and kernel version, are you using (do `uname -a` from the shell)

Also do you want held times, or do you want to know whether something's been pressed or clicked - looks like the latter from that example as you're not doing anything with the hold time?

**Comment by TJQuin** [comment]
Sorry I meant to say, but forgot to add that.  I am using bluetooth and have connected it to a windows PC once.  When I do uname -a it prints: Linux raspberrypi 5.4.51-v7+ #1333 SMP Mon Aug 10 16:45:19 BST 2020 arm7l GNU/Linux.  For the most part I am needing it just for when they are clicked or held, not as much for hold times.  I am using it to move something around on thrusters and mainly just need it to output values for which thrusters should fire and by how much. At this point the only issue seems to be that the triggers are not outputting anything.

**Comment by tomoinn** [comment]
Okay, so I'll take a look later (busy with the day job at the moment!). If you just want to see whether something's been pressed at all (rather than whether it's held *right now*) you need to do something like this:

```python
from approxeng.input.selectbinder import ControllerResource

while True:
    try:
        with ControllerResource() as joystick:
            joystick.check_presses() # Get pressed buttons to this point
            if joystick.presses.l2:
                # Do something if l2 was clicked at any point since the last check_presses call
```

This is better, because suppose you check every second. If you quickly click a button it's probably not held at the point you check, but the above code will tell you that the button was clicked even though it's not being held down now. You should only use the hold values if you care about how long a button has been held, i.e. you want to trigger an action if you hold a button for more than a second, that kind of thing.

You can also read multiple axes in one go, which might make your code a bit cleaner (I prefer accessing by attributes like this, but you could use the index notation, the `foo[...]` instead):

```python
lstick_x, lstick_y = joystick.lx, joystick.ly
```

Although in this case there's very little harm in just using the values directly (technically they could change between the comparison and the usage, but I don't think you care here). There's no runtime cost in reading properties like this.

If you're using Python3.8 you can simplify further with assignment expressions:

```python
if r_held := joystick.r2:
    print(f'right trigger: {rt_analog := joystick.rt}')
```

None of this actually fixes your problem, but hopefully it's useful anyway (also Python 3.8 assignment expressions, the `:=` operator, are great). I'll find a Pi and put the latest OS on it later and see if I can figure out why it's not working for you :)

**Comment by TJQuin** [comment]
I got time to just play around with the numbers in the xboxone.py file and actually was able to find which ones were connected to the triggers.  They were 9 and 10 for the right and left triggers in that order in case this comes up again.  Thanks for the help!
